"use strict";
const scenarios={advance:{state:"enemy=ahead, energy=ready",cell:{r:0,c:1},action:"ADVANCE",before:{x:72,y:110,enemy:250},after:{x:132,y:110,enemy:250},effect:"agent moved +60px toward enemy"},retreat:{state:"enemy=close, energy=low",cell:{r:1,c:0},action:"RETREAT",before:{x:145,y:110,enemy:225},after:{x:85,y:110,enemy:225},effect:"agent moved −60px away from enemy"},fire:{state:"enemy=aligned, weapon=ready",cell:{r:1,c:1},action:"FIRE",before:{x:80,y:110,enemy:245,shot:false},after:{x:80,y:110,enemy:245,shot:true},effect:"projectile became visible"}};
const colours=[["#5865f2","#22c55e"],["#f59e0b","#ef4444"]];
const select=document.querySelector("#scenario"),run=document.querySelector("#run"),reset=document.querySelector("#reset");
const policy=document.querySelector("#policy"),pctx=policy.getContext("2d"),before=document.querySelector("#before"),bctx=before.getContext("2d"),after=document.querySelector("#after"),actx=after.getContext("2d");
function chosen(){return scenarios[select.value]}
function drawPolicy(s){pctx.clearRect(0,0,320,160);for(let r=0;r<2;r++)for(let c=0;c<2;c++){pctx.fillStyle=colours[r][c];pctx.fillRect(c*160,r*80,160,80);pctx.strokeStyle="#0c1020";pctx.lineWidth=4;pctx.strokeRect(c*160,r*80,160,80)}pctx.strokeStyle="#fff";pctx.lineWidth=6;pctx.strokeRect(s.cell.c*160+4,s.cell.r*80+4,152,72)}
function drawWorld(ctx,w){ctx.clearRect(0,0,320,220);ctx.fillStyle="#11182d";ctx.fillRect(0,0,320,220);ctx.strokeStyle="#29324f";for(let x=0;x<320;x+=40){ctx.beginPath();ctx.moveTo(x,0);ctx.lineTo(x,220);ctx.stroke()}ctx.fillStyle="#60a5fa";ctx.beginPath();ctx.arc(w.x,w.y,18,0,Math.PI*2);ctx.fill();ctx.fillStyle="#fb7185";ctx.beginPath();ctx.arc(w.enemy,w.y,18,0,Math.PI*2);ctx.fill();if(w.shot){ctx.strokeStyle="#fde047";ctx.lineWidth=5;ctx.beginPath();ctx.moveTo(w.x+20,w.y);ctx.lineTo(w.enemy-20,w.y);ctx.stroke()}}
function render(runAfter=false){const s=chosen();drawPolicy(s);drawWorld(bctx,s.before);drawWorld(actx,runAfter?s.after:s.before);document.querySelector("#state").textContent=s.state;document.querySelector("#address").textContent=`row ${s.cell.r}, column ${s.cell.c}`;document.querySelector("#action").textContent=s.action;document.querySelector("#trace").innerHTML=`<span>state observed</span><span>cell (${s.cell.r},${s.cell.c}) selected</span><span>${s.action} decoded</span><span>${runAfter?s.effect:"run to apply action"}</span>`}
select.addEventListener("change",()=>render(false));run.addEventListener("click",()=>render(true));reset.addEventListener("click",()=>render(false));render(false);